### ISSUE TITLE
`latest` API parameter does not seem to work as expected

### ISSUE THREAD

**Issue by JackPGreen** [foojayio/discoapi#95]
This _might_ be user error.

I want to download (say) the latest version of Semeru JDK 11, for Linux/x64.

[The documentation](https://github.com/foojayio/discoapi?tab=readme-ov-file#get-the-download-link-of-a-package) says I should use `latest=available`, but [if I do that](https://api.foojay.io/disco/v3.0/packages?distro=semeru&jdk_version=11&package_type=jdk&operating_system=linux&architecture=x64&latest=available) I get the following response:
```
{
  "result": [
    {
      "id": "e001e5341739cb1a86454e2bf4758eb2",
      "archive_type": "tar.gz",
      "distribution": "semeru",
      "major_version": 11,
      "java_version": "11.0.22",
      "distribution_version": "11.0.22",
      "jdk_version": 11,
      "latest_build_available": true,
      "release_status": "ga",
      "term_of_support": "lts",
      "operating_system": "linux",
      "lib_c_type": "glibc",
      "architecture": "x64",
      "fpu": "unknown",
      "package_type": "jdk",
      "javafx_bundled": false,
      "directly_downloadable": true,
      "filename": "ibm-semeru-open-jdk_x64_linux_11.0.22_7_openj9-0.43.0.tar.gz",
      "links": {
        "pkg_info_uri": "https://api.foojay.io/disco/v3.0/ids/e001e5341739cb1a86454e2bf4758eb2",
        "pkg_download_redirect": "https://api.foojay.io/disco/v3.0/ids/e001e5341739cb1a86454e2bf4758eb2/redirect"
      },
      "free_use_in_production": true,
      "tck_tested": "unknown",
      "tck_cert_uri": "",
      "aqavit_certified": "unknown",
      "aqavit_cert_uri": "",
      "size": 205750292,
      "feature": []
    },
    {
      "id": "81408b9d636baab491c46b2948299907",
      "archive_type": "tar.gz",
      "distribution": "semeru",
      "major_version": 11,
      "java_version": "11.0.22",
      "distribution_version": "11.0.22",
      "jdk_version": 11,
      "latest_build_available": false,
      "release_status": "ga",
      "term_of_support": "lts",
      "operating_system": "linux",
      "lib_c_type": "glibc",
      "architecture": "x64",
      "fpu": "unknown",
      "package_type": "jdk",
      "javafx_bundled": false,
      "directly_downloadable": true,
      "filename": "ibm-semeru-certified-jdk_x64_linux_11.0.22.0.tar.gz",
      "links": {
        "pkg_info_uri": "https://api.foojay.io/disco/v3.0/ids/81408b9d636baab491c46b2948299907",
        "pkg_download_redirect": "https://api.foojay.io/disco/v3.0/ids/81408b9d636baab491c46b2948299907/redirect"
      },
      "free_use_in_production": true,
      "tck_tested": "no",
      "tck_cert_uri": "",
      "aqavit_certified": "yes",
      "aqavit_cert_uri": "https://github.com/ibmruntimes/semeru11-certified-binaries/releases/download/jdk-11.0.22%2B7_openj9-0.43.0/ibm-semeru-certified-jdk_x64_linux_11.0.22.0.tap.zip",
      "size": 219470559,
      "feature": []
    }
  ],
  "message": "2 package(s) found"
}
```

It's returned:
- `ibm-semeru-open-jdk_x64_linux_11.0.22_7_openj9-0.43.0.tar.gz` with `latest_build_available`=`true`
- `ibm-semeru-certified-jdk_x64_linux_11.0.22.0.tar.gz` with `latest_build_available`=`false`

I _think_ that:
- `latest=available` should have filtered out any `latest_build_available`=`false`
- a `semeru-certified` JDK should have a `distribution` of `semeru_certified`

**Comment by JackPGreen** [comment]
This is no longer occurring - is it actually fixed, or intermittent?

**Comment by HanSolo** [comment]
Should be fixed, the update of pkgs runs on different times for each distribution, so it might take some time for each distribution to be updated/cleaned up

**Comment by JackPGreen** [comment]
> It's returned:
> 
> * `ibm-semeru-open-jdk_x64_linux_11.0.22_7_openj9-0.43.0.tar.gz` with `latest_build_available`=`true`
> * `ibm-semeru-certified-jdk_x64_linux_11.0.22.0.tar.gz` with `latest_build_available`=`false`
> 
> I _think_ that:
> 
> * `latest=available` should have filtered out any `latest_build_available`=`false`

This looks to have been fixed
> * a `semeru-certified` JDK should have a `distribution` of `semeru_certified`

This is still occuring for `ibm-semeru-certified-jdk_x64_linux_11.0.22.0.tar.gz`

**Comment by JackPGreen** [comment]
> Indeed there was a bigger issue behind that thing...already fixing it...will come with the next deployment...probably over the weekend...thx for reporting it 👍🏻


> > * `latest=available` should have filtered out any `latest_build_available`=`false`
> 
> This looks to have been fixed

No rush from my side but this has regressed.

**Comment by JackPGreen** [comment]
This is still occuring.
Another [reproducer](https://api.foojay.io/disco/v3.0/packages?distro=zulu&jdk_version=17&package_type=jdk&libc_type=libc,glibc&operating_system=linux&architecture=x64,amd64&archive_type=tar.gz&archive_type=tar.xz&javafx_bundled=false&latest=available&directly_downloadable=true):
```
{
  "result": [
    {
      "id": "f723cae200a477884dac55a7d44616e4",
      "java_version": "17.0.18",
      "distribution_version": "17.64.17",
      "latest_build_available": false
    },
    {
      "id": "8cd55d6d7d9b9985b94c7756f20ac95c",
      "java_version": "17.0.18+8",
      "distribution_version": "17.64.15",
      "latest_build_available": true
    }
  ],
  "message": "2 package(s) found"
}
```

**Comment by HanSolo** [comment]
problem here is that the Java version of the second pkg is 17.0.18+8 which is greater than 17.0.18 which makes it the latest version. The distribution version is vice versa but because the distribution version is not standardized across all distributions I stick to the Java version which is taken often from the filename etc.

**Comment by JackPGreen** [comment]
> problem here is that the Java version of the second pkg is 17.0.18+8 which is greater than 17.0.18 which makes it the latest version. The distribution version is vice versa but because the distribution version is not standardized across all distributions I stick to the Java version which is taken often from the filename etc.

That makes sense (and these kind of issues are why I wanted to use an API instead of implementing it myself!).

Maybe _both_ should be tagged latest and the caller can decide what to do (including throwing an error)?

The technically incorrect (but simple solution...) is simply to consider the `latest=available` filter broken and filter on the client-side instead. Which probably isn't the behaviour you want to encourage.

**Comment by HanSolo** [comment]
Yeah I need to take a look at that, I'm currently on a trip but over the upcoming weekend there should be time to take a closer look at that. Probably will be something like if the distribution version is a valid semver version, take the latest version of the java version and the distribution version, otherwise stick to the java version. But even that can be tricky because Azul Zulu uses valid semver versions that are totally different from the java version. As said...need to take a look 😁
